### ISSUE TITLE
Feature Request: Open Folder Button On Series Info/Group Info Tab

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/ShokoClient#206]
Currently the only way to open the folder location for the selected series is to go to the episodes tab, expand an episode and at the bottom click the open folder button. It would be nice if we had an open folder button on the main series info tab as well as on the group info tab for series with multiple entries.

**Comment by AreFinstad** [comment]
i have been missing this one, not sure if i have already made an issue on it tho a few years back.
its only one issue tho, the files isnt always in the same folder.
at times they may be on another drive or moved into a season/special folder for TVDB managment.

we need a folder utility that can move everything in a series quickly are do it right.
even if the drive is full (then it should try to move things out of the drive and gather series on other places for it to make room for the series already in place in the full drive).

there is alot of things that should/could be better with the Folders of JMM, like English naming, Renaming folders (for new series that might not have official English names when you got the first few episodes) sorting folders to TVDB season standards (should not be hard at all i think) and many other small things.

a button might be nice, but there is a lot of buts about it because people might have it spread around (since JMM does not care where it is anyway)

**Comment by AreFinstad** [comment]
isnt this technically here now with the files tab of the series? just a thought. think thats enough @ElementalCrisis

**Comment by ElementalCrisis** [comment]
Yeah, a single button would not make sense anyways if your files were in multiple locations.
